[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "odin"
author = "Naglis Jonaitis"
author-email = "naglis@mailbox.org"
home-page = "https://naglis.me/"
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
requires = [
    "lxml==4.4.0",
    "defusedxml==0.6.0",
    "yarl==1.3.0",
    "parso==0.5.1",
]
requires-python="~=3.7"
description-file="README.rst"

[tool.flit.metadata.requires-extra]
test = [
    "pytest-cov==2.7.1",
    "flake8==3.7.8",
    "flake8-comprehensions==2.1.0",
    "mypy==0.720",
]
dev = [
    "pre-commit==1.17.0",
]

[tool.flit.scripts]
odin = "odin.main:main"

[tool.flit.entrypoints."odin.check"]
attribute_override = "odin.checks.xml:AttributeOverride"
button_classes = "odin.checks.xml:ButtonClasses"
data_file_inclusion = "odin.checks.addon:DataFileInclusion"
directory_permissions = "odin.checks.path:DirectoryPermissions"
duplicate_record_fields = "odin.checks.xml:DuplicateRecordFields"
duplicate_view_fields = "odin.checks.xml:DuplicateViewFields"
field_attrs = "odin.checks.python:FieldAttrs"
file_permissions = "odin.checks.path:FilePermissions"
ir_cron_state_code = "odin.checks.xml:IrCronStateCode"
ir_model_access_no_group = "odin.checks.addon:IrModelAccessNoGroup"
manifest_filename = "odin.checks.addon:ManifestFilename"
manifest_keys = "odin.checks.python:ManifestKeys"
noupdate = "odin.checks.xml:NoUpdate"
redundant_t_attf = "odin.checks.xml:RedundantTAttf"
route_kwargs = "odin.checks.python:RouteKwargs"
search_string = "odin.checks.xml:SearchString"
track_visibility_always = "odin.checks.python:TrackVisibilityAlways"
tree_string = "odin.checks.xml:TreeString"